### ISSUE TITLE
[firebase_auth] compilation error uprgading from 0.15.3 to 0.15.4

### ISSUE THREAD

**Issue by tianhaoz95** [FirebaseExtended/flutterfire#1885]
**Describe the bug**
When I upgrade firebase_auth from v0.15.3+1 to v0.15.4, the following error appear in compilation:

```bash
Error: The method 'confirmPasswordReset' isn't defined for the class 'FirebaseAuthPlatform'.
```

details can be found in the check run https://github.com/tianhaoz95/iwfp/pull/265/checks?check_run_id=411215259#step:12:57

**To Reproduce**
1. compile a project with firebase_auth 0.15.3 or below
2. upgrade to 0.15.4
3. compile again
4. see the compilation error

**Expected behavior**
It should compile and execute without crashing.

**Additional context**
The compilation was executed in ubuntu-latest in GitHub Actions.

**Comment by 2ZeroSix** [comment]
there is an error in transitive dependency `confirmPasswordReset` is implemented in `firebase_auth_platform_interface` 1.1.3.
As hotfix you could run `flutter pub upgrade` or (if you don't want to upgrade other packages for some reason) find `firebase_auth_platform_interface` in `pubspec.lock` and change it like this:
```
  firebase_auth_platform_interface:
    dependency: transitive
    description:
      name: firebase_auth_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.5"
```

**Comment by tianhaoz95** [comment]
It worked! Thanks!

**Comment by tianhaoz95** [comment]
@2ZeroSix does it mean `firebase_auth` forgot to bump its dependency of `firebase_auth_platform_interface` in its `pubspec.yaml`?

**Comment by 2ZeroSix** [comment]
It would be nice to add tests with `flutter pub downgrade` to prevent this type of issues

**Comment by tianhaoz95** [comment]
@2ZeroSix I think you are right. It would be nice to have a regression test for this. Can you elaborate more on the idea you had in mind or post a pointer to similar test here?

**Comment by 2ZeroSix** [comment]
@tianhaoz95 I found a few possible places to add this in ci scripts. Basically we need to run `build-examples` action twice, with newest possible packages and with downgraded. I'm not sure if we should run other actions twice as well 🤔 
- this line is causing actions to run via flutter_plugin_tools. ~If we want to run every action twice (for new and downgraded) this is the best place to add additional step.~ It seems that results of build step is used in next steps. 
https://github.com/FirebaseExtended/flutterfire/blob/a0b51b59d60a1b08b0e7d886cd6977740603f8fe/script/incremental_build.sh#L53
I hope the best way is to add additional tests like these below in `.cirrus.yml` with additional `flutter pub downgrade` step and removed tests steps (`java-test`, `firebase-test-lab`, `drive-examples`)
https://github.com/FirebaseExtended/flutterfire/blob/a0b51b59d60a1b08b0e7d886cd6977740603f8fe/.cirrus.yml#L41-L74
https://github.com/FirebaseExtended/flutterfire/blob/a0b51b59d60a1b08b0e7d886cd6977740603f8fe/.cirrus.yml#L95-L112
https://github.com/FirebaseExtended/flutterfire/blob/a0b51b59d60a1b08b0e7d886cd6977740603f8fe/.cirrus.yml#L131-L137

**Comment by 2ZeroSix** [comment]
@tianhaoz95 I've made mistake yesterday, `flutter pub downgrade` should be executed in every example, so it probably should be implemented as additional command in `flutter_plugin_tools`
here's `build_examples` command for reference
https://github.com/flutter/plugin_tools/blob/145a3d5de5ec9270441a77565082dcc8d90a7d3c/lib/src/build_examples_command.dart#L13-L105

**Comment by Ehesp** [comment]
Closing - confirmPasswordReset support is now available in the latest plugin version.
