### ISSUE TITLE
[firebase] Problem when run after upgrade Flutter to 2.0.4

### ISSUE THREAD

**Issue by paulo-coutinho** [FirebaseExtended/flutterfire#5667]
Hi,

After run flutter upgrade to version 2.0.4 (latest) and run my app i get this errors:

```
/Users/paulo/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-1.0.0/ios/Classes/FLTFirebaseCrashlyticsPlugin.h:8:9: 'Flutter/Flutter.h' file not found
```

```
/Users/paulo/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.2/ios/Classes/FLTFirebaseCorePlugin.h:8:9: fatal error: 'Flutter/Flutter.h' file not found
#import <Flutter/Flutter.h>
        ^~~~~~~~~~~~~~~~~~~
1 error generated.
2 errors generated.
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
Could not build the application for the simulator
```

Can anyone have any help?

**Comment by darshankawar** [comment]
@paulo-coutinho 
There's similar open issue describing your case, https://github.com/FirebaseExtended/flutterfire/issues/5660
Please follow-up there for updates.
Closing this as duplicate.
