### ISSUE TITLE
firebase_core Unable to build with firebase_core: 0.4.4+2

### ISSUE THREAD

**Issue by TylerSustare** [FirebaseExtended/flutterfire#2087]
## **Describe the bug**
This bug is representing the comment I made here on the closed issue. https://github.com/flutter/flutter/issues/35670#issuecomment-592769263 
Even trying  @sensuikan1973's suggestion in the linked issue didn't work.
```
• flutter clean
• Clean Build Folder from Xcode
• delete Podfile.lock

But, this didn't work.

So, I deintegrate pod.

cd ios
pod deintegrate
pod install
 ```

## **To Reproduce**
Attempting to build and run an iOS app with `firebase_core: ^0.4.4+2` lead to 
```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Xcode build done.                                            5.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/tsustare/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.4+2/darwin/Classes/FLTFirebaseCorePlugin.m:6:9: fatal error: 'UserAgent.h' file not found
    #import "UserAgent.h"
            ^~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description
Could not build the application for the simulator.
```

## **Expected behavior**
Starting the app using `firebase_core: ^0.4.4+2` the same way it does when I use `firebase_core: 0.4.3+3`

## **Additional context**
the rest of my firebase packages in  **pubspec.yaml**
``` yaml
dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4

  firebase_core: 0.4.3+3
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.2+1
  firebase_analytics: ^5.0.11
```

**Comment by NMNguyen** [comment]
Same problem :(

**Comment by ch-muhammad-adil** [comment]
I downgraded the version as mentioned above, and it caused conflict with firestore cloud storage version. Than i downgraded that too at `cloud_firestore: 0.13.2` and i was able to install the app

**Comment by cadaniel** [comment]
Having the same problem. 

For anyone like me who kept the ^ in the version, remove it otherwise it will keep using newer versions.

**Comment by msnowshadali** [comment]
• flutter clean
• Clean Build Folder from Xcode
• delete Podfile.lock

But, this didn't work.

So, I deintegrate pod.

cd ios
pod deintegrate
pod install

**Comment by kjmj** [comment]
> I downgraded the version as mentioned above, and it caused conflict with firestore cloud storage version. Than i downgraded that too at `cloud_firestore: 0.13.2` and i was able to install the app

I can confirm that this fixed it for me. Downgrading to `cloud_firestore: 0.13.2` and `firebase_core: 0.4.3+3` works.

**Comment by pojoba02** [comment]
What i did that work for me was removing  ^ sign in the package version and  flutter clean.
firebase_auth: 0.15.4
cloud_firestore: 0.13.4
firebase_core: 0.4.4
hopefully that works for you guys..

**Comment by nicolascav** [comment]
> What i did that work for me was removing ^ sign in the package version and flutter clean.
> firebase_auth: 0.15.4
> cloud_firestore: 0.13.4
> firebase_core: 0.4.4
> hopefully that works for you guys..

It worked for me too!

**Comment by bbanderson** [comment]
YEAHHH You saved me a lot! Thanks

> What i did that work for me was removing ^ sign in the package version and flutter clean.
> firebase_auth: 0.15.4
> cloud_firestore: 0.13.4
> firebase_core: 0.4.4
> hopefully that works for you guys..

**Comment by vpxoxo** [comment]
> What i did that work for me was removing ^ sign in the package version and flutter clean.
> firebase_auth: 0.15.4
> cloud_firestore: 0.13.4
> firebase_core: 0.4.4
> hopefully that works for you guys..

this works for me too!!! thanks a lot 😍

**Comment by ingsoto83** [comment]
> What i did that work for me was removing ^ sign in the package version and flutter clean.
> firebase_auth: 0.15.4
> cloud_firestore: 0.13.4
> firebase_core: 0.4.4
> hopefully that works for you guys..

It works!!! Thanks!

**Comment by loushou** [comment]
@everyone - can anyone please add a comprehensive list of package versions that would work with the reduced versions of firebase_core please? I have run through the releases list, and used the versions listed there that are prior to the latest firebase_core release... however this does not appear to do the trick. I feel like there are a few un tagged versions that are just not in the list. Thanks in advance for putting this together!

**Comment by NoahFlowa** [comment]
> What i did that work for me was removing ^ sign in the package version and flutter clean.
> firebase_auth: 0.15.4
> cloud_firestore: 0.13.4
> firebase_core: 0.4.4
> hopefully that works for you guys..

This works for me!  Thank you!

**Comment by StephanCassel** [comment]
I had similar problems.

  firebase_core: ^0.4.4+2
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4
  firebase_storage: ^3.1.3
  firebase_analytics: ^5.0.11

Did not build. Tons of errors.

Previous settings works just fine:
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  firebase_storage: ^3.0.6
  firebase_analytics: ^5.0.2

I then removed: 
**implementation 'com.google.firebase:firebase-core:16.0.4'**  from my build.gradle
It has been in my build.gradle for long time without any harm. 
Why I have put it there I do not know. 

And I took the lates firebase plugins again, with ^ sign:

  firebase_core: ^0.4.4+2
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4
  firebase_storage: ^3.1.3
  firebase_analytics: ^5.0.11

And now it builds perfect. Both Android and iOS for debug and release. 

Summary: 
I love Flutter. It has really changed development processes dramatically. 
I hate Flutter when I need to update 30+ dependencies in my YAML. 
I love 😍Flutter😍 even more again when everything words some hours later and I can continue coding.

**Comment by andesappal** [comment]
To reproduce the build failure, just create a new Flutter project, and add Cloud Firestore as a dependency, then try running the project.

**Comment by andesappal** [comment]
(also add the Google services info plist)

**Comment by awhitford** [comment]
It appears that PR #2099 should resolve this.  I'm eagerly waiting for that to be released as this is impacting many modules.

**Comment by saultrejo** [comment]
> What i did that work for me was removing ^ sign in the package version and flutter clean.
> firebase_auth: 0.15.4
> cloud_firestore: 0.13.4
> firebase_core: 0.4.4
> hopefully that works for you guys..

Downgrading firebase_core to 0.4.4 worked for me. Thanks a lot.

**Comment by iapicca** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/2084

**Comment by bhenav** [comment]
Same problem :(
  firebase_core: 0.4.4+2
  firebase_analytics: 5.0.11
  firebase_messaging: 6.0.12

**Comment by iamatulkumar** [comment]
same problem

**Comment by jmagman** [comment]
Fixed by https://github.com/FirebaseExtended/flutterfire/pull/2169.

**Comment by iamatulkumar** [comment]
dependencies:
     firebase_core: 0.4.4
     firebase_remote_config: ^0.3.0+3
     firebase_auth: 0.15.0    ---> remove ^ 

dependency_overrides:
    firebase_core: 0.4.4

Works for me. thanks a lot (y)

**Comment by pointmdca** [comment]
should now be fixed with firebase_core 0.4.4+3: Fix for missing UserAgent.h compilation failures.
Some of the other packages got this update as well.

**Comment by dhust** [comment]
> should now be fixed with firebase_core 0.4.4+3: Fix for missing UserAgent.h compilation failures.
> Some of the other packages got this update as well.

Did not work with firebase_core 0.4.4+3. It never copied over the firebase_core-0.4.4 folder in the Dart Packages folder.

**Comment by edufolly** [comment]
> > should now be fixed with firebase_core 0.4.4+3: Fix for missing UserAgent.h compilation failures.
> > Some of the other packages got this update as well.
> 
> Did not work with firebase_core 0.4.4+3. It never copied over the firebase_core-0.4.4 folder in the Dart Packages folder.

Verify if the pubspec.yaml file is correct. Try to execute ```flutter pub cache repair```.

In my latest iOS build, I needed to clear Xcode cache.
```rm -rf ~/Library/Developer/Xcode/DerivedData```

In iOS folder, delete ```Podfile.lock``` file and  ```Pods``` folder, than execute ```pod upgrade```.

**Comment by dhust** [comment]
I e

> > > should now be fixed with firebase_core 0.4.4+3: Fix for missing UserAgent.h compilation failures.
> > > Some of the other packages got this update as well.
> > 
> > 
> > Did not work with firebase_core 0.4.4+3. It never copied over the firebase_core-0.4.4 folder in the Dart Packages folder.
> 
> Verify if the pubspec.yaml file is correct. Try to execute `flutter pub cache repair`.
> 
> In my latest iOS build, I needed to clear Xcode cache.
> `rm -rf ~/Library/Developer/Xcode/DerivedData`
> 
> In iOS folder, delete `Podfile.lock` file and `Pods` folder, than execute `pod upgrade`.

I ended up going back to 0.4.4 and it creates the folder.
