### ISSUE TITLE
[firebase_auth] iOS doesn't build when upgrade to 1.15.x

### ISSUE THREAD

**Issue by tianhaoz95** [FirebaseExtended/flutterfire#1679]
**Describe the bug**
Flutter app doesn't build on iOS when upgrading `firebase_auth: ^0.14.0+5` to `firebase_auth: ^0.15.3`. The build failed with 2 errors:
```bash
    /Users/runner/hostedtoolcache/flutter/1.12.13-hotfix.5-stable/x64/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.3/ios/Classes/FLTFirebaseAuthPlugin.m:493:38: error: no known class method for selector 'credentialWithProviderID:IDToken:rawNonce:accessToken:'
          credential = [FIROAuthProvider credentialWithProviderID:provider
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/runner/hostedtoolcache/flutter/1.12.13-hotfix.5-stable/x64/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.3/ios/Classes/FLTFirebaseAuthPlugin.m:502:38: error: no known class method for selector 'credentialWithProviderID:IDToken:rawNonce:'
          credential = [FIROAuthProvider credentialWithProviderID:provider
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**To Reproduce**
1. go into `pubspc.yaml`
2. upgrade `firebase_auth: ^0.14.0+5` to `firebase_auth: ^0.15.3`
4. run `flutter pub get && flutter build ios --release --no-codesign`

**Expected behavior**
It should build without throwing error.

**Additional context**
Tool versions:
```bash
Flutter 1.13.3-pre.71 • channel master • https://github.com/flutter/flutter.git
Framework • revision beb86d2cc4 (89 minutes ago) • 2019-12-18 14:03:01 -0800
Engine • revision 866b158c4b
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 c9d89d55a6)
```

**Comment by eugenejeonme** [comment]
Oh... I think this should be corrected quickly.

**Comment by tianhaoz95** [comment]
@eugenejeonme will there be a hot fix release for that?

**Comment by eugenejeonme** [comment]
> @eugenejeonme will there be a hot fix release for that?

Sorry, no 😢

**Comment by tianhaoz95** [comment]
> > @eugenejeonme will there be a hot fix release for that?
> 
> Sorry, no

Does it mean I will need to wait for the next scheduled release? If so, do you know when that will be?

**Comment by eugenejeonme** [comment]
> > > @eugenejeonme will there be a hot fix release for that?
> > 
> > 
> > Sorry, no
> 
> Does it mean I will need to wait for the next scheduled release? If so, do you know when that will be?

I don't know, Only they know, Firebase Team.
And I don't know why to show this error.
It is definitely the Method that exists in Apple's official document. 🤔 So I need an idea to solve.
-> https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Classes/FIROAuthProvider

**Comment by jpv123** [comment]
Same problem here. It's weird Firebase team didn't saw this error when making the new release. Hopefully they fix this quickly

**Comment by SogoGolf** [comment]
we're also seeing this, very frustrating

**Comment by emekalites** [comment]
I fixed this temporarily by running `pod update` in ios folder

**Comment by iapicca** [comment]
Hi @tianhaoz95 
did the solution proposed by @emekalites work for you?
thank you

**Comment by asada03** [comment]
pod update solved the issue for me too.

**Comment by tianhaoz95** [comment]
Yes, `pod update` fixes the issue. Does that mean the root cause is a missing script in the package?

**Comment by netdesignr** [comment]
`pod update` did the job dor the time being

**Comment by jffiorillo** [comment]
`pod update` fixes the issue.

**Comment by eugenejeonme** [comment]
YES! Updated FirebaseAuth version to 6.4.1 by `pod update`, also other packages too updated. So It's resolved to me. :)

**Comment by tianhaoz95** [comment]
I agree, it's an one time fix. Everything works fine afterwards.

**Comment by eugenejeonme** [comment]
> I agree, it's an one time fix. Everything works fine afterwards.

So could you close this issue card? :)?

**Comment by tianhaoz95** [comment]
sure!

**Comment by ened** [comment]
The actual fix should be to bump the dependency on Firebase in the .podspec file, isn't it? https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/ios/firebase_auth.podspec

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by comm1x** [comment]
Seems, to fix this issue, need just to update version on cocoapods dependencies (Firebase from 6.10.0 to 6.20.0 and several others). And there is no fix. Nice 👍
